---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: damage
  namespace: go72hog
  labels:
    app: damage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: damage
  template:
    metadata:
      labels:
        app: damage
    spec:
      containers:
      - name: damage
        image: ghcr.io/mtze/pedelec-damage:latest
        ports:
          - containerPort: 8080
            name: damage-api