---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  namespace: go72hog
  labels:
    app: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
      - name: location
        image: ghcr.io/mtze/pedelec-location:latest
        ports:
          - containerPort: 8080
            name: location-api