---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  namespace: go72hog
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
      - name: reservation
        image: ghcr.io/mtze/pedelec-reservation:latest
        ports:
          - containerPort: 8080
            name: reservation-api